language: android
dist: trusty
android:
  components:
    - build-tools-25.0.3
    - android-26
    - add-on
    - extra
    - addon-google_gdk-google-19
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'