language: android
android:
  components:
    - build-tools-21.1.1
    - extra-android-support
    - addon-google_gdk-google-19
install:
  - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.0.2"

